### PR TITLE
Cia file notice for hbl wrapper

### PR DESCRIPTION
**Pull request by MechanicalDragon0687**

### CODE REVIEW

**Comment by Plailect** [comment]
This notice was in the past only used to tell the user which files to download when there are multiple. In this case, there's only one file on the release. Why is this needed?

**Comment by MechanicalDragon0687** [comment]
For some reason people see source options and downoad them since all others seem to indicate which file...

**Comment by MechanicalDragon0687** [comment]
What about a note to not download source files then since that is global for all of them?

**Comment by Plailect** [comment]
I don't think this is really needed and this has been sitting for a while. Closing unless further discussion of this comes up.

**Pull request closed without merging**
