### PR TITLE
Add kartdlphax-usm

### PR DESCRIPTION
**Pull request by PabloMK7**
**Description**

This pull request brings back kartdlphax using USM. I have decided not to overwrite the exiting kartdlphax page as it is still a valid method for consoles on firmware lower than 11.16.

### CODE REVIEW

**Comment by PabloMK7** [comment]
I now just realised pull request #2091 exists ;_;. I have reviewed it and I think there are some sections there that could be improved. Please let me know how to proceed.

**Comment by lifehackerhansol** [comment]
IMO, we should only have one kartdlphax page, so I'm more in favour of the other PR.

You can suggest changes there.

**Comment by PabloMK7** [comment]
The problem with the other PR is that it completely overwrites the original kartdlhax page. Suggesting changes there would be totally overwriting the existing changes.

**Comment by PabloMK7** [comment]
The problem is not with the diff. The other PR replaces the existing kartdlphax instructions with the new ones, while this PR creates a different page. The other PR contributor would need to restore the existing page and add the same txt file in this PR

**Comment by lifehackerhansol** [comment]
I'm not exactly certain if we want another kartdlphax page. 
@lilyuwuu what's your opinion?

**Comment by lilyuwuu** [comment]
As it stands, if we're only going to use USM with kartdlphax, then it's probably better to keep it as "Installing boot9strap (kartdlphax)". On the other hand, based on guide statistics, about 20% of people are doing BB3-Fredtool, presumably due to broken shoulder buttons, so we could presume that anyone doing kartdlphax would end up in the same situation.

**Comment by lifehackerhansol** [comment]
I think the goal of this PR is less about having an archived version and more having the 11.15 version publicly facing so people on 11.15 can just go straight to universal-otherapp instead.

I'm of the argument that it's not necessary to keep both versions of kartdlphax, particularly since kartdlphax itself is quite literally _never_ used. Seedminer is still an invincible method and kartdlphax will always be a "if Seedminer doesn't work do this" method. In fact, the only time I've ever recommended anyone to follow it was people with a banned console or a launch model O3DS which is fundamentally incompatible with Seedminer. This would mean that a very large chunk of users updated their console to follow Seedminer and failed. Hence I don't see many people on 11.15 and lower following it.

**Comment by PabloMK7** [comment]
Closed as suggested

**Pull request closed without merging**
