### PR TITLE
Blad best girl patch 1

### PR DESCRIPTION
**Pull request by BladBestGirl**
**Description**

### CODE REVIEW

**Comment by BladBestGirl** [comment]
Accident, my bad

**Comment by lifehackerhansol** [comment]
lmao

**Comment by BladBestGirl** [comment]
lmao indeed

**Comment by eip618** [comment]
why are you making a fork lmao

**Comment by BladBestGirl** [comment]
> why are you making a fork lmao

for my own personal website

i like the 3ds guide skin

**Pull request closed without merging**
