### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by evolvedhat**
Create README.md

### CODE REVIEW

**Comment by lilyuwuu** [comment]
Not sure what exactly the purpose of this is? A README would be good but should contain information about the repository (e.g. What it is, contribution conventions, build instructions), not just a copy of get-started.

**Comment by lifehackerhansol** [comment]
I don't remember off the top of my head how our Jekyll is set up. But this can break the website due to how Jekyll works.

I am against this patch being merged.

**Comment by evolvedhat** [comment]
No worries. I'm doing this as a part of a school project (has to be documentation only). I copied some basic information from the website just to give a better idea of the project.

**Comment by eip618** [comment]
> No worries. I'm doing this as a part of a school project (has to be documentation only). I copied some basic information from the website just to give a better idea of the project.

Did you seriously make a garbage PR to a project with over 2.8k commits and 75 contributors just for the sake of a school project? Bad form dude.

**Comment by adrot** [comment]
I propose to close this already as it has no use whatsoever or warrant any further discussion.

**Comment by eip618** [comment]
> I propose to close this already as it has no use whatsoever or warrant any further discussion.

i propose you are correct

**Pull request closed without merging**
