### PR TITLE
Add short explanations for components of the Seedminer finalization step 

### PR DESCRIPTION
**Pull request by Redmega**
Adds a short description of what DSP1 and `ctr-no-timeoffset` are responsible for in the *What You Need* section.

Thanks to users `ahrigatø` and `bungiefan(what does the guide say?)` from Discord, who explained what `DSP1` and `ctr-no-timeoffset` were for.

### CODE REVIEW

**Comment by Plailect** [comment]
The download space is not a good place for those. Notice that there is a section almost right above that where the purpose of other homebrew applications is explained.

**Comment by Redmega** [comment]
Good point @Plailect. I didn't put these there because they're not mentioned there before, but I'll unify them now.

**Comment by Plailect** [comment]
The purpose of DSP1 is so that homebrew applications have sound, nothing to do with CIA formatted games.

**Comment by Redmega** [comment]
Ah, that was a misunderstanding of mine. Should be good to go now.

**Comment by Plailect** [comment]
Alright, now just fix the capitalization and I'll merge (other descriptions do not begin with any capitalization).

**Comment by Redmega** [comment]
Whoops

**Pull request merged**
