### PR TITLE
prevent seedminer things from going wrong :P

### PR DESCRIPTION
**Pull request by Gruetzig**
-add flashcart sd notice, seems to be an issue, example from NH https://discord.com/channels/196618637950451712/247557068490276864/1045096506807570432 
-add steps for generating a Nintendo 3DS folder or the actual ID0 if it hasnt been generated yet this is never done and some people use the wrong ID0 apparently

### CODE REVIEW

**Comment by lilyuwuu** [comment]
Not personally a big fan of the changes here.

- Most people don't have flashcarts. It isn't reasonable for us to potentially confuse people (by talking about flashcarts, which most people don't have) by adding lines to account for uncommon edge cases.
- People who don't have a Nintendo 3DS folder are already covered by the "If you don't have a Nintendo 3DS folder" bullet point. Adding "power on then power off" instructions for all users is kinda clunky and doesn't account for people who don't have an SD card or whose SD card isn't properly inserted or something (hopefully to be fixed if/when #2148 is merged).

@lifehackerhansol thoughts?

**Comment by Gruetzig** [comment]
> Most people don't have flashcarts. It isn't reasonable for us to potentially confuse people (by talking about flashcarts, which most people don't have) by adding lines to account for uncommon edge cases.

That's true, did think of that but wanted to hear your thoughts.
> People who don't have a Nintendo 3DS folder are already covered by the "If you don't have a Nintendo 3DS folder" bullet point. 

Yes, but I was more focusing on generating the correct ID0, because I often see people in the assistance channels saying
something like "When I did Seedminer I only had one ID0, but then a second one appeared and I ignored it", shouldnt happen unless the 3DS hasn't been booted up with SD yet. Then they place the Nintendo DSiWare folder in wrong id0 and generate a wrong movable and f00d43d5.bin file which can be prevented with these steps. Only having steps for missing Nintendo 3DS folder is not enough in my opinion.

**Comment by lifehackerhansol** [comment]
Man I wonder where all these people get their extraneous ID0s...

There isn't really a clear-cut solution for this. Yes a power off and power on solves this. But that would just make multiple power on and off for people who end up with two ID0s by doing that.

Why can't we just force making a backup of Nintendo 3DS right at the start? That way it's somewhat a clean slate? I don't really like this idea either but it's better than having to reboot like 5 times just to figure out a 32-char number

**Comment by MechanicalDragon0687** [comment]
if they get a valid movable.sed, then the id0 is for their system meaning it went through a system transfer or format and was not booted to home menu after. This is a niche case and i dont think we need extra steps to handle this

**Comment by Gruetzig** [comment]
I guess my ideas are all bad :(

**Pull request closed without merging**
