### PR TITLE
Add Pretendo to the Finalizing GM9 script for when NNID shuts down

### PR DESCRIPTION
**Pull request by mirrormirrorontheweb**
Don't merge till it does tho

### CODE REVIEW

**Comment by Gruetzig** [comment]
pretendo has a documentation people should just be redirected to, whatever this is i dont like it

**Comment by mirrormirrorontheweb** [comment]
> pretendo has a documentation people should just be redirected to, whatever this is i dont like it

I was just gonna add it to the finishing gm9 script

**Comment by mirrormirrorontheweb** [comment]
ima add it to the script when i get home

**Comment by lifehackerhansol** [comment]
This doesn't belong on the guide.

Maybe it's worth it on the [wiki](https://wiki.hacks.guide/). But I assume by that point Pretendo would have their own instructions, which would be good to link in [Things to do](https://wiki.hacks.guide/wiki/3DS:Things_to_do).

**Pull request closed without merging**
