### PR TITLE
create troubleshooting for jp n3ds error 032-0420

### PR DESCRIPTION
**Pull request by Gruetzig**
thanks to luigoalma for mentioning this fix

### CODE REVIEW

**Comment by lifehackerhansol** [comment]
Thoughts on just making this a step in the guide?

**Comment by Gruetzig** [comment]
do you mean something like:
`If you receive error 032-0420, follow [this troubleshooting guide](link to troubleshooting)`?

**Comment by Gruetzig** [comment]
or add this long troubleshooting to the page directly

**Comment by Gruetzig** [comment]
I dont see an existing troubeshooting that can be combined with the new one

**Comment by lifehackerhansol** [comment]
> I dont see an existing troubeshooting that can be combined with the new one it doesnt crash, no fancy flashing, no update prompt

I'd argue an error code is a crash, but sure. (what do we define as a "crash" anyway?)

I guess we will consider the other error codes later. I think this is fine.

**Comment by lifehackerhansol** [comment]
I rewrote this troubleshooting a bit to clean up. Does it look alright?

**Comment by Gruetzig** [comment]
a bit, lol, yeah looks good

**Pull request merged**
