### PR TITLE
clarify cfw check

### PR DESCRIPTION
**Pull request by Gruetzig**
(sent picture of the cfw check)
smol💀💀💀💀 — Today at 7:17 PM
did you do it or not
nah — Today at 7:17 PM
no
smol💀💀💀💀 — Today at 7:17 PM
why not
its the first section of the guide
nah — Today at 7:17 PM
i didnt think i had to bc i never got to actually downloading anything

### CODE REVIEW

**Comment by lilyuwuu** [comment]
i'm kinda iffy on this - it seems kind of unnecessary and anyone who is purposely skipping it won't necessarily suddenly not skip it just because they potentially see a line

**Comment by Gruetzig** [comment]
maybe it is unnecessary but its not harmful and even if it doesnt help 99,9% of all people it still helps 0,1%.

**Comment by lilyuwuu** [comment]
there is potential harm in that it's kind of unnecessarily scary the way it is currently worded

**Comment by Gruetzig** [comment]
where is it scary

**Comment by lilyuwuu** [comment]
"do not skip this" implies that something bad will happen to the console if it is skipped, which is rarely the case

**Comment by Gruetzig** [comment]
fine

**Pull request closed without merging**
