### PR TITLE
Refactor selecting.js

### PR DESCRIPTION
**Pull request by lifehackerhansol**
**Description**
- Each method is now its own function
  - Pass identical arguments to each function for unity
- Call each function in desired order from redirect()
- More comments
- General stability improvements to enhance the user experience

### CODE REVIEW

**Comment by lifehackerhansol** [comment]
I make code work, I never said it was pretty

**Comment by lifehackerhansol** [comment]
I've tested everything, I think; can someone test locally and double check?

**Comment by Gruetzig** [comment]
at your service, hansol

**Comment by lifehackerhansol** [comment]
pushed to HEAD

**Pull request closed without merging**
