### PR TITLE
was fun while it lasted

### PR DESCRIPTION
**Pull request by lifehackerhansol**

### CODE REVIEW

**Review by lilyuwuu — COMMENTED** [review]
might also wanna remove the path from _main.js

**Comment by lifehackerhansol** [comment]
> might also wanna remove the path from _main.js

done

**Comment by lilyuwuu** [comment]
might wanna unremove hbl-usm from this pr pending recent releases(?)

**Comment by lifehackerhansol** [comment]
hbl usm left intact for now, but removed from js as it is currently unused

we can add it back there once we have a guide path

**Pull request merged**
