### PR TITLE
workflow: update actions

### PR DESCRIPTION
**Pull request by Margen67**
See commit(s).

### CODE REVIEW

**Comment by eip618** [comment]
is this 'best practice' or are there any practical changes?

**Comment by lifehackerhansol** [comment]
Best practice

Functionally nothing should change

**Comment by MaruceJontiSandbor** [comment]
Hey Margen, your Angel Hare stuff was DMCAd, can you link that stuff to on your twitter. I followed you.

**Comment by lifehackerhansol** [comment]
Made redundant by https://github.com/hacks-guide/Guide_3DS/commit/ae719cf9c174306a39780a91c32f131b67e350c4

**Comment by Margen67** [comment]
> Made redundant by [ae719cf](https://github.com/hacks-guide/Guide_3DS/commit/ae719cf9c174306a39780a91c32f131b67e350c4)

configure-pages can be updated to v5: https://github.com/actions/configure-pages/tags
Should I make a new PR?

**Pull request closed without merging**
