### PR TITLE
Update torrent list

### LINKED ISSUE #1678: R4iGold3DS-backup.bin (HW 8) flash
It's missing from the guide. Tested and working. The cart has an 8 on the back.
[R4iGold3DS-backup.zip](https://github.com/hacks-guide/Guide_3DS/files/3117588/R4iGold3DS-backup.zip)

SHA256:
`
eb950acbcf5f1be918be3982524ef615a60ef815c06a548b2734fd32fb6189c6  R4iGold3DS-backup.bin
`

ntrboot.log (injecting ntrboot):
```
[INFO]: R4iGold: Init
[NOTICE]: R4iGold: HW Revision = 00000000
[NOTICE]: R4iGold: HW Type = b7db5bb5
[INFO]: R4iGold: readFlash(addr=0x00000000, size=0x200000)
[INFO]: R4iGold: Injecting ntrboot
[INFO]: R4iGold: readFlash(addr=0x001f0000, size=0x10000)
[INFO]: R4iGold: writeFlash(addr=0x001f0000, size=0x10000)
[INFO]: R4iGold: readFlash(addr=0x001f0000, size=0x10000)
[INFO]: R4iGold: writeFlash(addr=0x001f0000, size=0x10000)
[INFO]: R4iGold: readFlash(addr=0x00080000, size=0x10000)
[INFO]: R4iGold: writeFlash(addr=0x00080000, size=0x10000)
```

ntrboot.log (restoring flash):
```
[INFO]: r4isdhc.hk: Init
[ERROR]: r4isdhc.hk: trySecureInit: init key1 (key = 0) failed: 11
[ERROR]: r4isdhc.hk: trySecureInit: init key1 (key = 1) failed: 11
[ERROR]: r4isdhc.hk: trySecureInit: init key1 (key = 2) failed: 11
[ERROR]: r4isdhc.hk: Secure init failed!
[INFO]: r4isdhc.hk: Shutdown
[INFO]: R4iGold: Init
[NOTICE]: R4iGold: HW Revision = 00000000
[NOTICE]: R4iGold: HW Type = b7db5bb5
[INFO]: R4iGold: readFlash(addr=0x00000000, size=0x200000)
[INFO]: R4iGold: writeFlash(addr=0x00080000, size=0x10000)
[INFO]: R4iGold: writeFlash(addr=0x001f0000, size=0x10000)
```

### LINKED ISSUE #1729: Add 11.12/11.13 nfirm to hardmod page
11.12/11.13 NATIVE_FIRM is missing on hardmod page so why not fix that

### LINKED ISSUE #1738: CTRTransfer images for CHN/KOR/TWN
We should have these images prepared at some point.

- [ ] CHN
- [ ] KOR
- [ ] TWN

### PR DESCRIPTION
**Pull request by lifehackerhansol**
**Description**

This PR:
- Adds 11.15.0 CTRTransfers
- Adds all remaining NFIRMs to RSS feed
- Removes unused torrents
- Fixes small bug in `rss.py`
- Fixes small bug in `_tables.scss`, which affected the hardmod NFIRM table (thanks @lilyuwuu for reporting)
- Closes #1678 
- Closes #1729
- Closes #1738

### CODE REVIEW

**Comment by lifehackerhansol** [comment]
Complete. Please review before merge.

**Comment by lifehackerhansol** [comment]
O3DS TWN CTR image has been added.

We now have the latest images for all regions (yay?)

**Comment by lifehackerhansol** [comment]
We now have all NFIRMs present on the guide.

**Review by lilyuwuu — APPROVED** [review]
Looks good to me! Every torrent seems to be able to (eventually) retrieve metadata.

**Comment by lifehackerhansol** [comment]
Part of that is that I'm like the only one seeding.

Though that should change with the RSS updates... probably... hopefully...

**Review by radostin04 — APPROVED** [review]

**Comment by lifehackerhansol** [comment]
The `contribute` page was updated with some instructions with seeding.

**Pull request merged**
