### PR TITLE
treewide: miscellaneous changes

### PR DESCRIPTION
**Pull request by TophattedWasTaken**
Currently:

1. Remove 7zip reference in the hardmod page
2. Update config.ini for Luma3DS v13.2
3. Remove unused images

### CODE REVIEW

**Comment by TophattedWasTaken** [comment]
Might add more to this, depends on what I find while looking through the guide

**Comment by TophattedWasTaken** [comment]
making sure I didn't delete anything in use, expect great image purge in 10ish minutes

**Comment by TophattedWasTaken** [comment]
Pretty sure everything is good

**Review by irowiki — APPROVED** [review]
Looks good, @lifehackerhansol might be able to figure out why those images were making crowdin mad.

**Comment by TophattedWasTaken** [comment]
why do a couple only have soundhax what

**Review by lifehackerhansol — APPROVED** [review]

**Pull request merged**
